---
  - name: Install GPG key for SubLimeText
    apt_key:
      url: https://download.sublimetext.com/sublimehq-pub.gpg
      state: present

  - name: Add repo for Sublime Text
    apt_repository:
      repo: "deb https://download.sublimetext.com/ apt/stable/"
      state: present
      filename: sublime

  - name: Install Sublime Text
    apt:
      state: present
      pkg: sublime-text
      update_cache: yes
  